#!/usr/bin/env python

import subprocess

def options(opt):
	opt.recurse('..')
	opt.load('compiler_cxx')

def configure(conf):
	conf.recurse('..')
	conf.load('compiler_cxx')

def build(bld):
	bld.recurse('..')
	bld.program(source='main.cpp',
	            target='test',
			    use='binpath',
				lib='binpath',
			    includes='../src')

def run(ctx):
	subprocess.check_call("./build/test")
